use std::collections::HashMap;

use crate::broadcast::Broadcast;
use crate::graph::{Graph, GraphNode};
use crate::render::{render_crate_surface_compact, summarize_crate_surface};

/// Generate the AI context markdown for a single repo.
pub fn generate_context(
    node: &GraphNode,
    graph: &Graph,
    broadcasts: &HashMap<String, Broadcast>,
) -> String {
    let mut out = String::new();

    out.push_str("## Ecosystem Context (auto-generated by archon)\n\n");
    out.push_str(&format!(
        "You are working in **{}** — {}\n\n",
        node.name, node.description
    ));

    // Dependencies table.
    if !node.depends_on.is_empty() {
        out.push_str("### Your dependencies\n\n");
        out.push_str("| Repo | Role | Key types & traits |\n");
        out.push_str("|------|------|--------------------|");

        for dep_name in &node.depends_on {
            let role = graph
                .find_node(dep_name)
                .map(|n| n.role.to_string())
                .unwrap_or_else(|| "?".to_string());

            let summary = broadcasts
                .get(dep_name)
                .map(|b| {
                    b.crates
                        .iter()
                        .map(summarize_crate_surface)
                        .collect::<Vec<_>>()
                        .join("; ")
                })
                .unwrap_or_else(|| {
                    graph
                        .find_node(dep_name)
                        .map(|n| n.description.clone())
                        .unwrap_or_default()
                });

            out.push_str(&format!("\n| {} | {} | {} |", dep_name, role, summary));
        }
        out.push_str("\n\n");
    } else {
        out.push_str("### Your dependencies\n\nNone — this is a root node.\n\n");
    }

    // Dependents.
    if !node.dependents.is_empty() {
        out.push_str("### Who depends on you\n\n");
        for dep_name in &node.dependents {
            let desc = graph
                .find_node(dep_name)
                .map(|n| n.description.as_str())
                .unwrap_or("");
            out.push_str(&format!("- **{}** — {}\n", dep_name, desc));
        }
        out.push('\n');
    } else {
        out.push_str("### Who depends on you\n\nNo other repos currently depend on this.\n\n");
    }

    // Own public API surface (from broadcast).
    if let Some(broadcast) = broadcasts.get(&node.name) {
        let has_api = broadcast.crates.iter().any(|c| {
            !c.types.is_empty() || !c.traits.is_empty() || !c.functions.is_empty()
        });

        if has_api {
            out.push_str("### Your public API surface\n\n");
            if !node.provides.is_empty() {
                out.push_str(&format!(
                    "Provides: {}\n\n",
                    node.provides
                        .iter()
                        .map(|p| format!("**{}**", p))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            for crate_surface in &broadcast.crates {
                let rendered = render_crate_surface_compact(crate_surface);
                if !rendered.is_empty() {
                    out.push_str(&format!("#### {}\n\n", crate_surface.name));
                    out.push_str(&rendered);
                    out.push('\n');
                }
            }
        }
    }

    out.trim_end().to_string()
}

/// Wrap context in managed section markers for injection.
#[allow(dead_code)]
pub fn wrap_in_markers(context: &str) -> String {
    format!(
        "<!-- ARCHON:CONTEXT:BEGIN -->\n{}\n<!-- ARCHON:CONTEXT:END -->",
        context
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::broadcast::*;
    use crate::manifest::Role;

    fn test_graph() -> Graph {
        Graph {
            generated_at: "2026-03-08T00:00:00Z".into(),
            nodes: vec![
                GraphNode {
                    name: "core".into(),
                    description: "Core computation engine".into(),
                    role: Role::Core,
                    depends_on: vec![],
                    provides: vec!["core-api".into()],
                    dependents: vec!["ext".into()],
                },
                GraphNode {
                    name: "ext".into(),
                    description: "Extension layer".into(),
                    role: Role::Extension,
                    depends_on: vec!["core".into()],
                    provides: vec!["ext-api".into()],
                    dependents: vec![],
                },
            ],
        }
    }

    #[test]
    fn generate_context_for_extension() {
        let graph = test_graph();
        let mut broadcasts = HashMap::new();
        broadcasts.insert(
            "core".into(),
            Broadcast {
                repo: "core".into(),
                version: "0.1.0".into(),
                generated_at: "2026-03-08".into(),
                crates: vec![CrateSurface {
                    name: "core-lib".into(),
                    types: vec![TypeDef {
                        name: "Graph".into(),
                        kind: TypeKind::Struct,
                        doc: Some("Main graph type".into()),
                        fields: vec![],
                        variants: vec![],
                        generic_params: vec![],
                    }],
                    traits: vec![],
                    functions: vec![],
                    reexports: vec![],
                    contracts: vec![],
                }],
            },
        );

        let node = graph.find_node("ext").unwrap();
        let ctx = generate_context(node, &graph, &broadcasts);

        assert!(ctx.contains("You are working in **ext**"));
        assert!(ctx.contains("| core | core |"));
        assert!(ctx.contains("`Graph`"));
        assert!(ctx.contains("No other repos currently depend on this"));
    }

    #[test]
    fn generate_context_for_core() {
        let graph = test_graph();
        let broadcasts = HashMap::new();

        let node = graph.find_node("core").unwrap();
        let ctx = generate_context(node, &graph, &broadcasts);

        assert!(ctx.contains("root node"));
        assert!(ctx.contains("**ext**"));
    }
}
